### ISSUE TITLE
tntbuild failed on windows x86

### ISSUE THREAD

**Issue by ratones** [trueinteractions/tint2#101]
When I run "tntbuild --clean package.json" the tntbuild script exits on "writing icon for windows" with the message "object is not a function". Also, if I skip this step by commenting the line in tntbuild.js, I get the same error on "writing manifest for windows"
<pre>
packaging res\applications.png 
packaging index.html
packaging main.js
packaging package.json
linking res/applications.png
linking index.html
linking main.js
linking package.json
reading windows icon
creating icon data
creating windows application
finalizing windows
writing icon for windows
Error: object is not a function
</pre>
The build fails on the test folder too.

I have build tint for x86 using instructions from the git readme. 
I have VS2010 SP1 and python 2.7.8. installed.

**Comment by romovs** [comment]
It seems that unlike tools.sh, tools.bat doesn't patch TINT_WINDOWS_EXECUTABLE in tntbuild.js with tint runtime - hence the above error.

As a work around I tried to specify the runtime using --windows-native switch but it throws a VC++ runtime error:

    Assertion failed: end <= source_len, file ..\..\libraries\node\src\smalloc.cc, line 280

This might be due to my VS2013 though.

**Comment by trevorlinton** [comment]
@romvos Hm, it appears to be a bit difficult to track down, the unit tests do not fail nor do some of the examples i've tried. Can you post what your package.json file looks like?

**Comment by trevorlinton** [comment]
@romovs 

AH, i just re-read your initial post and apparently missed it in my first pass.  Note that the bundling process and "release" only works on OS X. This is where tntbuild has a pass on it that inserts the base64 encoded binary into tntbuild.js.  There is no step for this on windows as our release process is only for OSX.  I'll see what we can do about porting over the release steps for windows.

As a side note, why are you building this from scratch?  We have binary releases available; or did you need a 32-bit build?.

**Comment by romovs** [comment]
@trevorlinton 

Yeah I just needed a 32-bit build mostly because I am using a 32-bit machine for development at the moment. 
Not sure if we will ever actually need/want to package a 32-bit version of the app, but I guess it would be a nice option to have.

**Comment by trevorlinton** [comment]
This should be fixed with https://github.com/trueinteractions/tint2/commit/39aeb76cf1b4290b5e12a4cd7fabba48263d0d68 you'll still need to specify the 32-bit windows exec as a runtime when running tntbuild. 

Feel free to reopen if you have further issues.
