### ISSUE TITLE
Transparent Windows

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint2#103]
Hi Trevor, 
looking through the documentation, I don't see anything for creating transparent windows like in Tint 1. Is there an effective way to create a transparent window with transparent webview? Can this also be transparent to clicks?

**Comment by trevorlinton** [comment]
@JohnLouderback 

Hi John, we do actually have transparency enabled on OS X, however Windows only supports transparency when not using the GPU (thus a large performance hit if we enable it on windows).

There's a secret property on both the Window and WebView object called 'transparent'. (https://github.com/trueinteractions/tint2/blob/master/modules/WebView/WebView_mac.js#L659), we'll introduce it to the public docs once we've fully supported all of the corner cases in Windows.  I'll leave this open to update you as to the status as it moves along.

As per support contract we'll shift priority to getting transparency working (well) in Windows as soon as possible.

**Comment by trevorlinton** [comment]
@JohnLouderback 

BTW, you can use ``win.backgroundColor = 'rgba(0,0,0,0)';`` to make the window transparent, however, it only works on OS X.  We'll be working on getting this to work on Windows as well.

-t

**Comment by trevorlinton** [comment]
This should be fixed now (see my previous comments on the closed thread here: https://github.com/trueinteractions/tint2/issues/107#issuecomment-87939047). For anyone else who stumbles on this, transparent windows in windows is supported with tint-chromium here: https://github.com/trueinteractions/tint-chromium/ (or if you're on OS X just the regular old webview packaged with tint).

If you continue to have issues, feel free to reopen either this or that one.

**Comment by JohnLouderback** [comment]
Works like a charm! Thanks!
