### ISSUE TITLE
webview debugger

### ISSUE THREAD

**Issue by 7immy** [trueinteractions/tint2#105]
How can i access the webview debugger?

Many thanks :)

**Comment by trevorlinton** [comment]
Hi 7immy, we currently don't have support for the debugger on Windows (IE) but we can open up a remote debugging port for WebKit on OS X, it would be a private (shh its a secret!) feature within WebView.   

Also, we'll be publishing a chromium node module for Tint on monday that will have debugging support (to both open a debugging port or debugging window) on the chromium WebView. You can also go that direction (but would need to include chromium's resources, which are not trivial ~80mb).

**Comment by trevorlinton** [comment]
@7immy We've added the chromium module for tint; you can find information on it (and using devtools) at https://github.com/trueinteractions/tint-chromium/ Note that it currently only supports windows, but we'll be shortly adding OS X support (including dev tools).

**Comment by trevorlinton** [comment]
As a side note, if you're using OS X you can open up the Safari built in web inspector by running:

```javascript
webview.native('_setAllowsRemoteInspection', process.bridge.objc.YES);
webview.native('configuration')('preferences')('_setDeveloperExtrasEnabled', process.bridge.objc.YES);
```

Then right clicking on the webview and clicking "Inspect Element". This is not recommended to use this code in production or deployed apps, as its using private API's.

**Comment by mrkev** [comment]
YES! Thanks! :raised_hands:
