### ISSUE TITLE
tools.bat VS 2013 quick fix

### ISSUE THREAD

**Issue by petitben** [trueinteractions/tint2#109]
Hi,

Just wanted to mention there is a %VS110COMNTOOLS% left @ line 168 - most probably a copy/paste mistake I presume. Please replace the line 168 of tools.bat:

_if defined VS120COMNTOOLS if exist "%VS110COMNTOOLS%\..\..\vc\vcvarsall.bat" (_

by: 

_if defined VS120COMNTOOLS if exist "%VS120COMNTOOLS%\..\..\vc\vcvarsall.bat" (_

Thanks and keep up the good work - tint2 is great :-) !

**Comment by trevorlinton** [comment]
@petitben Thanks! I've fixed this with: https://github.com/trueinteractions/tint2/commit/1b93bb047bff004150c06cb927b235f86cfb2def

- Trevor
