### ISSUE TITLE
Tint2 installer .pkg does not open on OS X (10.10.3)

### ISSUE THREAD

**Issue by evanpaschke** [trueinteractions/tint2#114]
Hi,
I was attempting to install tint2 using the `tint-2.1.8-x64-osx` .pkg, but the installer fails to open the package and displays the error:

'The operation couldn’t be completed. (com.apple.installer.pagecontroller error -1.). Couldn't open "tint.pkg".'

Do I need to set permissions or move files before attempting to open the package?

Thanks!

**Comment by trevorlinton** [comment]
Hm, i'm not able to replicate it on the four macbooks i've tried. Googling around several sources seem to indicate that it depends on how the pkg is executed seems to affect whether it successfully runs.  What browser are you downloading tint on?  Safari, Chrome or Firefox?

Also, are you double clicking on the downloaded file or going straight from your finder?

Here's other references that may help, i'll continue to try and figure out if there's something odd happening, any other tidbits would be helpful.

https://github.com/alterstep/dnscrypt-osxclient/issues/9
https://discussions.apple.com/message/15094512#15094512

**Comment by evanpaschke** [comment]
Total user error on my part, sorry about this!

Unarchiver was unwrapping the package and I was attempting to open the `tint.pkg` within the installer package. I was downloading using Chrome and had Chrome set to auto-open the download (thus unwrapping it in Unarchiver). 

Thanks for following up on this! Tint2 is looking great, migrating from Node Webkit.
