### ISSUE TITLE
Compiling Windows application on Yosemite 10.10.3 ends early

### ISSUE THREAD

**Issue by ajay-gandhi** [trueinteractions/tint2#115]
When compiling a Windows application using `tntbuild`, the process simply stops 5 steps before completing. It doesn't throw any visible errors.

    $ tntbuild --clean --no-osx-build ./package.json
    ...
    [15159 of 15169] linking app.js
    [15160 of 15169] linking package.json
    [15161 of 15169] linking server.js
    [15162 of 15169] linking setup.js
    [15163 of 15169] linking studentcenter.js
    [15164 of 15169] reading windows icon

This is using Tint 2.1.8.

**Comment by trevorlinton** [comment]
@ajay-gandhi What is the structure of the package.json package? Can you send the png icon for windows?  Is the icon a 512x512 png RGBA format?

**Comment by ajay-gandhi** [comment]
Good call, the icon was 192x192. Increasing the size solved the issue. On a side note, do applications for Windows need to be compiled on Windows?

**Comment by trevorlinton** [comment]
@ajay-gandhi Glad to hear it helped, i'll leave this open until we add some checks to the dimensions of the png.

OSX can compile Windows applications and vice versa, doesnt matter which platform the build is on.

**Comment by trevorlinton** [comment]
Added checks on https://github.com/trueinteractions/tint2/commit/f7c79f8144951647fd7ad4313b13c8b302ce44b5

Closing this out.
