### ISSUE TITLE
Add support for registering global keyboard shortcuts

### ISSUE THREAD

**Issue by murphyrandle** [trueinteractions/tint2#116]
It'd be super-duper-mega-ultra-fantastic to be able to bind to global shortcuts.

Here's an example from Electron's docs of what their API looks like: https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md

Sorry, I wish this were a pull-request instead of an issue :|

**Comment by trevorlinton** [comment]
Not a problem, you can use Menu events to assign commands back to a javascript callback (such as cntrl+c, cmd+c, etc.) We'll look into adding global application level keyboard shortcuts that dont require a menu.

**Comment by JohnLouderback** [comment]
👍 This feature will be useful to me as well.

**Comment by trevorlinton** [comment]
Added on https://github.com/trueinteractions/tint2/commit/fb925bbb217eb44c62b7692b9ec0f4ff400d811b it'll be in 2.1.10 due out tomorrow.

Closing this out, if you have questions/problems feel free to reopen

**Comment by murphyrandle** [comment]
Awesome! Thank you!
