### ISSUE TITLE
Linux build guide: missing dependencies

### ISSUE THREAD

**Issue by xHN35RQ** [trueinteractions/tint2#119]
Also requires `libgirepository1.0-dev` on Ubuntu 14.04 otherwise the following error message is encountered on config:

    Package gobject-introspection-1.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gobject-introspection-1.0' found
    gyp: Call to 'pkg-config --libs gobject-2.0 gobject-introspection-1.0' returned exit status 1.

Also I think it requires `systemtap-sdt-dev` on Ubuntu 14.04 otherwise build will not complete.

**Comment by trevorlinton** [comment]
Added to build steps in docs, thanks!
