### ISSUE TITLE
Linux build failure - gir failing to build

### ISSUE THREAD

**Issue by xHN35RQ** [trueinteractions/tint2#120]
Build failed on Ubuntu 14.04 64bit with following log: https://gist.github.com/xHN35RQ/5ac2a0bc7f7553dd1ed7

**Comment by trevorlinton** [comment]
@xHN35RQ the node runtime for gobject's is GIR, however GIR is only compatible with node 0.10.x, we're in the process of upgrading it to support node 0.12.x.  You can check the linux status here:

https://github.com/trueinteractions/tint2/wiki/Linux-Support-Status

**Comment by trevorlinton** [comment]
@xHN35RQ The build for GIR has been updated to node v0.12.  Feel free to reopen if you have any questions.
