### ISSUE TITLE
Feature: Container.focus()

### ISSUE THREAD

**Issue by tzmartin** [trueinteractions/tint2#123]
Is it possible to add focus methods to Containers and Windows, including Box and WebView?   

``System.clickAtControl(view)`` is not sufficient due to it repositioning the mouse x/y coordinates to center values.  I'm needing a simple focus event to change the current context.

Example:

```
view1 = new WebView();
view2 = new WebView();
view1.focus();
setTimeout(function() {
    view2.focus();
},1000);
```
Thoughts?

**Comment by trevorlinton** [comment]
Sounds great! Added on https://github.com/trueinteractions/tint2/commit/5720f763a99b99b489d661ce5b260cc153779c5d

Feel free to reopen if you have additional questions.  This will be in release v2.1.12 later this evening.
