### ISSUE TITLE
Handle console output in a webview

### ISSUE THREAD

**Issue by johansatge** [trueinteractions/tint2#124]
Hi,

I was wondering if there is a way (I may have missed it ?) to handle the console output: `console.log` calls, Javascript errors...

(More globally, I understood that for now there is no web inspector, at least on OSX.)

I did not find the answer in the [webview page](https://www.trueinteractions.com/tint2/docs/WebView.html).

Thanks !

**Comment by tzmartin** [comment]
I'm overriding console.log and global error events that pipes data from a WKWebView context to the native context for unified logging.  Logs are tagged, timestamped and color coded for easier debugging. 

Here is a snippet taken from an IDE that I'm developing:

```
// Override console.log (gracefully)
console.log = function (log) {
    return function () {
        var args = Array.prototype.slice.call(arguments);
        args.unshift('Editor-'+new Date().getTime().toString().substr(7, 6)); // Push milliseconds as first argument
        if (window.hasOwnProperty('postMessageToHost')) {
          window.postMessageToHost(JSON.stringify({event:'WKWebViewLog',data:args.join(' - ')}));
        } else {
          log.apply(console, args);
        }
    };
}(console.log);

window.onerror = function(errorMsg, url, lineNumber) {
  var str = 'Error: ' + errorMsg + ' Script: ' + url + ' Line: ' + lineNumber;
  if (window.hasOwnProperty('postMessageToHost')) {
    window.postMessageToHost(JSON.stringify({event:'WKWebViewError',data:str}));
  } else {
    console.log(str);
  }
}
```

**Example log**:

![Tint debugging](https://monosnap.com/file/v49Y1RPUveuY2Z3sqvdOke79M26a83.png)

**Comment by johansatge** [comment]
Beautiful !

Thanks.

**Comment by trevorlinton** [comment]
Just an fyi, I added console logging for convenience to the API, its now an event on the webview, also, freenode.net #tint.js if you want to chat, i'd love to hear about what you're all making.  Commit is on: https://github.com/trueinteractions/tint2/commit/ad6266e1dc1aac17eafd4472cbf8e5680fb33422

**Comment by johansatge** [comment]
Saw this, great :thumbsup:
