### ISSUE TITLE
Working with drag&dropped files

### ISSUE THREAD

**Issue by johansatge** [trueinteractions/tint2#131]
Hi,

I was wondering if there is a way to get the path of the files that are dropped on a `Window`.

I tried the following cases:

1. By using the `dragenter` and `drop` Javascript events in a `WebView`; this works well with multiple files, but the event does not return the files paths - which is logical as it works like a *standard* web browser.
2. By using a transparent `FileInput` control that would cover `100%` of the window dimensions; but (for now ?) this control seems to accept only one file at a time.

Is there an other way to achieve this ?

Thanks !

**Comment by trevorlinton** [comment]
Hi @johansatge 

I wouldn't recommend using the FileInput as its usually meant for singular operations in a form.  The FileDialog might be helpful, and allows you to select multiple files, and supports drag operations (although it runs as a modal sheet or new window).

Example:
```javascript
require('Common');
var mainWindow = new Window();
mainWindow.visible = true;

var fileDialog = new FileDialog();
fileDialog.allowMultiple = true;
fileDialog.on('select', function() {
  console.log(fileDialog.selection);
});
fileDialog.open(mainWindow);
```

The other option would be to support the drag sequence operations in objective-c/.NET here:
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DragandDrop/Concepts/dragdestination.html#//apple_ref/doc/uid/20000977-BAJBJFBG

These would return (for any Control) when the user is dragging something over, the content of it, the type of it and whether to accept/reject it. 

Does FileDialog work for your needs or are you looking for something more like a more sophisticated drag/drop event/delegate handlers?

**Comment by trevorlinton** [comment]
For reference: http://www.trueinteractions.com/tint2/docs/FileDialog.html

**Comment by johansatge** [comment]
Thanks for your quick reply !

I am already using a `FileDialog` control to help the user select a list of files to work with (it is triggered with a *Select files...* button available my UI).
But I also wanted the application to react when he drops directly the files on the main `Window`.

So I guess supporting the objective-c drag operations would be the right solution, even if I don't really know how to achieve this.

**Comment by trevorlinton** [comment]
The interface would probably work something like this:

```javascript
yourcontrol.on('drag', function( dragged ) {
  if(dragged.type === "image/png") {
   console.log(dragged.data); /* might be a url reference, might be a base64 data url. */
   return true;
  }  else {
   return false
  }
});
```

Effectively returning true/false lets the operating system know whether to render a focus highlight around your control and a + symbol or positive symbol or whether to just show that the user cannot drag the item here.

The interface may have to change a little if the OS requires first accepting then receiving the data. but that's the gist of it. If this works for you shouldn't be too hard to implement by the next release cycle.

**Comment by johansatge** [comment]
This looks nice; would it also work when dropping multiple files ?

Something like:

```javascript
yourcontrol.on('drag', function(dragged_files)
{
    for(var index = 0; index < dragged_files.length; index += 1)
    {
        var file = dragged_files[index];
        console.log(file.type); // image/png
        console.log(file.path); // /Users/tint/Desktop/my_image.png (Do we get the file path ? Or is it restricted like in the webview for security reasons ?)
        console.log(file.data); // base64 stuff
        if (file.type.search(/^image\//) === -1)
        {
            return false; // we only want images in our list
        }
    }
    return true;
});
```

If so, I would be happy to see this included in a future release !

It would open interesting new opportunities - I'm thinking about droplet apps for instance.

**Comment by trevorlinton** [comment]
@johansatge It actually serves a need i have on a project so its not without my own greedy concerns :).  That's a valid point that we'd need to pass in an array of dragged objects.  We'll roadmap it for 2.1.15, should be there sometime Monday.

Cheers,
Trevor

**Comment by trevorlinton** [comment]
added on https://github.com/trueinteractions/tint2/commit/383722203db88be388ca8de7731cd1dc3103a089 and https://github.com/trueinteractions/tint2/commit/51d2ae3038df681f9c4f7edc07db4e853354c68b

Closing this out, feel free to reopen if you have any questions.  This will be added on 2.1.15 due out tomorrow.

- Trevor

**Comment by johansatge** [comment]
Hi,

this works fine, thanks !

I got two questions;
* Is there a way to get the path of each dropped file ?
* Does the `dropped` event work on a `Webview` ?

**Comment by johansatge** [comment]
Answer to the first question: that seems possible but discouraged:

> Although you can support dragging file paths, in general, you should avoid doing so unless you are certain that the destination app will never be run in an app sandbox. If you use an NSString, OS X has no way to know whether that string should be interpreted as a path; thus, OS X does not expand the destination app’s sandbox to allow access to the file or directory at that location.
Instead, use an NSURL, a bookmark, or a filename pasteboard type.
[Source](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DragandDrop/Tasks/DraggingFiles.html)

Would it require a lot of work to implement this ?
IMO providing the path to the user is not a problem, he just has to be aware that this is an additional information (useful to get the filename for instance)
If he wants to read the content he will still have to use the `Buffer` object.

**Comment by brianmoquin** [comment]
FWIW, the quote above doesn't refer to dragging files and folders from the Finder onto components in your application; doing so does give one access to the complete path information (outside the context of a WebView).  Dragging and dropping files/folders into a component results in the "dropped" event callback receiving an array of objects each of which have a **.type** member set to "file" and a **.data** member set to a buffer containing a _file reference URL_.  In order to obtain the absolute path of each dropped item, you need to convert them.  Here's a function that does that:

```
var $ = process.bridge.objc;
require('path');
function realFilePath(refURL) {
    return decodeURI(($.NSURL("URLWithString", $(refURL.toString())))('filePathURL')('absoluteString')('UTF8String')).replace('file://','');
}
```

Note that this works for any Tint2 component configured to accept a 'file' drop type, _except for WebView components_.  AFAIK, Apple's WebKit, and WebKit as modified by Mozilla, used to have a security policy setting that could be changed to allow absolute paths to be obtained inside the browser, but they removed that capability entirely a few years ago, as did Chrome and everybody else.

One strange thing I discovered about the WebKit component is that I can successfully block individual files from being dragged from Finder into it using a "policy" event callback, but PDF files aren't blocked using that method; the content of the WebView component will be replaced by the PDF regardless.
