### ISSUE TITLE
Packaged app can't find index.html on OSX

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#132]
Hi,

I am using latest tint build on OSX

```
tint-2.1.14-x64-osx.pkg
osx => 10.10.2
tint -v => v0.12.4
```

There is an issue with this line:
```
webview.location = "app://index.html"
```

When i run a [hello world app](https://www.trueinteractions.com/tint2/docs/tutorial-gettingstarted.html) using `tint main.js` it behaves as expected loading my `index.html`

However, when i package the app...
```
rm -rf build/* ; tntbuild package.json --no-windows-build
```

...and try to run it, the webview doesnt load my `index.html` file, instead i have blank window

I tried to use `file://` schema instead of `app://`, but had same result
```
webview.location = "file://"+process.cwd()+"/index.html";
```

Another interesing thing i noticed is that setting StatusBar icon works as expected in both packaged and unpackaged app.
```
statusBar.image = 'app://icon-256.png';
```

This makes me think that the problem probably doesn't come from the `app://` protocol handler, but from `WebView`'s code

This issue looks similar to #93 

Any idea why this happens ?

Thanks

**Comment by trevorlinton** [comment]
@dchapkine We've fixed this with commit https://github.com/trueinteractions/tint2/commit/676bbdca7d1419a92d79e6666f6df52783ef4327

This will be in 2.1.15 to be released later this evening.  Thanks for reporting this!

- Trevor
