### ISSUE TITLE
Fresh Tint installation on fresh Windows 10 won't start

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint2#134]
When trying to run the ``tint `` command on a fresh copy of Windows 10 Preview I'm seeing the below error:
![win10tinterror](https://cloud.githubusercontent.com/assets/4743179/8067909/a50787cc-0ea5-11e5-95e5-cc7909412f41.PNG)
I checked to make sure the .NET framework was installed and it is. Any ideas? I haven't seen this issue on Windows 7. Both operating systems are 64 bit.

**Comment by trevorlinton** [comment]
Hm. Try taking the two DLL's included in Tint's install (msvcp120.dll and msvcr120.dll) and place them next to the executable (e.g., in the same folder) and see if that resolves the issue. My bet is Tint is explicitly asking for a versioned DLL when it should be asking for a generic DLL (e.g., msvcp or msvcr regardless the version)..

Keep me posted on this, i'll try and recreate it on a fresh install of Win7 tomorrow and see if it pulls up anything interesting.

**Comment by JohnLouderback** [comment]
When you say "the executable" are you referring to the Tint executable or the executable Tint produces. In this case, I'm running the ``tint`` command and so no executable is produced to my knowledge. My Tint directory already contains the aforementioned DLL files.
![tintfolder](https://cloud.githubusercontent.com/assets/4743179/8099629/b0dd431a-0fb4-11e5-8623-5432d722749e.PNG)

**Comment by trevorlinton** [comment]
@JohnLouderback I was unable to get Windows 10 to load, but i'm wondering if this is the garbage collection bug we found in Tint about a week ago.  We've been hunting it down since and have yet to find a solution. Needless to say its backlogged us for a bit and i'll post a fix up as soon as I can find one.  

In the meantime (if you can) try an earlier version such as 2.1.13/2.1.12.

**Comment by JohnLouderback** [comment]
Hey Trevor,
just wanted to keep ya up to date. I downgraded to 2.1.12, but I am still seeing the same error exactly. Something interesting I'm seeing is that ``tint`` won't run at all. Even ``tint -v`` shows the same error.

**Comment by JohnLouderback** [comment]
Hey all,

to anybody else having this issue, I needed to download and install the Visual C++ Redistributable. I took for granted that it was already on the system. You can download it here: https://support.microsoft.com/en-us/kb/2977003/ Installing that will fix the issue.

**Comment by trevorlinton** [comment]
@JohnLouderback I'll add something to the docs around this, it seems Windows removed the VC++ redistributable, i'm a bit confused as to how to resolve this other than to include the dll's when tntbuild runs.  I do believe the only two files from the distro you need will be msvcp120.dll and msvcr120.dll
