### ISSUE TITLE
FileDialog.allowAnyFileType crash

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#136]
If i set allowAnyFileType it crashes the app (on osx 10.10.3 with tint 2.1.15)

https://www.trueinteractions.com/tint2/docs/FileDialog.html#allowAnyFileType

```
require('Common');

var fileDialog = new FileDialog();
console.log(fileDialog.allowAnyFileType);
fileDialog.allowAnyFileType = true;
fileDialog.open();
```

output:

```
false
class.js:211
        throw e;
              ^
TypeError: error setting argument 2 - writePointer: Buffer instance expected as third argument
    at TypeError (native)
    at Object.writePointer (ref.js:723:11)
    at Object.set (ref.js:499:13)
    at Object.alloc (ref.js:529:13)
    at ForeignFunction.proxy (_foreign_function.js:50:22)
    at unwrapper (core.js:333:34)
    at ID.module.exports.Class.msgSend (class.js:205:34)
    at rtn (core.js:416:47)
    at FileDialog.Object.defineProperty.set (FileDialog.js:107:27)
    at Object.<anonymous> (/Users/.../file-dialog.js:5:29)

```

PS: It looks like even if allowAnyFileType is set to false by default, i can select any file. Is there any extension restriction when it's set to false ?

**Comment by trevorlinton** [comment]
@dchapkine Thanks for reporting this! Unfortunately our built in GUI scripts cant test file dialogs due ot security restrictions on OSX / Windows.  I've re-ran the file dialog unit tests by hand and everything looks good.  It seems they broke in a optimization pass, we've also added a warning to the commit view if the file dialog classes are changed to hopefully prevent this from happening again.

This will be up in 2.1.16 due out Monday. Feel free to reopen if you have further issues.
