### ISSUE TITLE
Question: tint and node version CLI

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#140]
Hey, after some pause I'm with tint hacking again :wine_glass: 

The question is just curiosity. When running `tint -v` command in bash it prints `0.12.4` which is version of node.js installed on my machine. I installed latest `2.1.16`  pkg. Does it mean that `tint` CLI just wraps `node`? I think it will be more useful to print actual tint's version instead of node's in CLI.

**Comment by trevorlinton** [comment]
@voronianski Yes, it does just wrap node, to be command-line level compatible with node it prints out the same CLI information.  To get nodes information you'll need to run ```node -e "console.log(process.versions)"```

There's the possibility of appending to the CLI output but my worry is it will lead to incompatibilities with various node scripts for corner cases.

Thoughts? We could always use different conventions for tint options such as -X,-v (similar to how GCC handles passing options to a linker)

**Comment by voronianski** [comment]
@trevorlinton I think it will be useful to add some tint specific options and commands to CLI (e.g. version, generate bundle etc.)

**Comment by trevorlinton** [comment]
@voronianski I'm not sure if this is spelled out in the docs but there is ```tntbuild``` to build a bundle (osx/win) and tntdbg (requires node-inspector installed globally) to debug tint.

I'll see about adding a flag to print out versions and generally the same info as node.

**Comment by voronianski** [comment]
@trevorlinton thanks for reminder, it seems that I saw info about `tntbuild` in docs somewhere.

**Comment by trevorlinton** [comment]
@voronianski We've added switches to tint but they're prefixed (similar to how gcc handles passing linker options) with -X,<commandline>  Currently we only have -v, and --version but perhaps we'll add more (let me know if you have any ideas). 

This will be in the upcoming 2.1.17 release, please let me know if you find other features you'd like for ocmmand line options and we can add them to tint.
