### ISSUE TITLE
Packaged apps: Menu and global hot keys are unresponsive; keyboard events ignored

### ISSUE THREAD

**Issue by tzmartin** [trueinteractions/tint2#142]
Hi there.  In dev, Menu hot keys are working fine, but fail when building using ```tntbuild```.  In fact all keyboard events are ignored for packaged apps, preventing webviews from receiving keyboard events.

However, if I run the binary directly from the command line, hot keys and keyboard events work.

```
./build/MacOS\ X/tint-app.app/Contents/MacOS/Runtime
```
Here's a small test case: https://gist.github.com/tzmartin/a6184690b3354a99bd37
(packaged apps are not working).

Tested 2.1.16, Mac

**Comment by trevorlinton** [comment]
I ran your test and none of the menu hot keys worked for a packaged or non-packaged app..  I found a resolution by commenting out the registerHotKey function.  It seems that registering a hot key invalidates the menu hot keys (and vice versa)..

More to come.

**Comment by trevorlinton** [comment]
Sorry this took so long to track down, we've added a fix in and unit test.  This will be included in the 2.20 release on Monday July 27th.

Feel free to reopen if you continue to have issues.

**Comment by tzmartin** [comment]
\m/ excellent
