### ISSUE TITLE
RegisterHotKey for arrows?

### ISSUE THREAD

**Issue by ricardoalcocer** [trueinteractions/tint2#152]
I noticed here https://github.com/trueinteractions/tint2/blob/0baeb479cd70240d488e401fb1ab4ff78facfa0f/modules/Application/Application_mac.js#L147 that registerHotKey accepts only 1-char strings.  Is there a way of registering a global Hot key for non-printable characters like keyboard arrows, function keys, etc?

**Comment by trevorlinton** [comment]
OSX uses one character for arrow keys and function key bindings:

```
enum {
    NSUpArrowFunctionKey            = 0xF700,
    NSDownArrowFunctionKey          = 0xF701,
    NSLeftArrowFunctionKey          = 0xF702,
    NSRightArrowFunctionKey         = 0xF703,
    NSF1FunctionKey                 = 0xF704,
    NSF2FunctionKey                 = 0xF705,
    NSF3FunctionKey                 = 0xF706,
    // other constants here
    NSUndoFunctionKey               = 0xF743,
    NSRedoFunctionKey               = 0xF744,
    NSFindFunctionKey               = 0xF745,
    NSHelpFunctionKey               = 0xF746,
    NSModeSwitchFunctionKey         = 0xF747
};
```

Meaning, you can use ```\uF700``` for the up arrow, etc.  For example:

```javascript
application.registerHotKey('\uf700','alt',function() { console.log('uparrow plus alt'); });
```

Registers an up key plus "alt" key as a hot key.

**Comment by trevorlinton** [comment]
If you continue to have problems with this, feel free to reopen.

**Comment by ricardoalcocer** [comment]
This totally works.  Thank you!

**Comment by tzmartin** [comment]
Helpful reference: http://osxnotes.net/keybindings.html
