### ISSUE TITLE
Bug in how "exclude" files are handled

### ISSUE THREAD

**Issue by ricardoalcocer** [trueinteractions/tint2#156]
In reference to a [previous thread](https://github.com/trueinteractions/tint2/issues/155), there appears to be a problem in the way exclusions are handled.  If I say: `"exclude" : ".git"`, this will not only exclude the `.git` folder, but any file within the project that has the word `git` in it.  In my case, I have a file called `mod_gitclone.js`, which after careful examination, never made it to the final packaged app.

**Comment by bral** [comment]
@ricardoalcocer I'm not able to test this out at the moment... but have you tried escaping the `.` ?

ex. `"exclude": "\.git"`

**Comment by ricardoalcocer** [comment]
@bral , that breaks the parsing:

```
"sources": {
    "directory": ".",
    "exclude":"\.git"
  }
```
leads to:

```
SyntaxError: Unexpected token .
    at Object.parse (native)
    at Object.$tint.loadbuilder (/usr/local/bin/tntbuild:31:28)
    at Object.<anonymous> (/usr/local/bin/tntbuild:2823:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:825:3
Error: Unexpected token .
```

**Comment by trevorlinton** [comment]
@ricardoalcocer Try "\\.git", the escape character should also be escaped, so its a double backslash, not a single.  Feel free to reopen this bug if you're still having issues.

Thanks,
Trevor

**Comment by trevorlinton** [comment]
er, for some reason github is removing our double backslashes, its " \ \ . g i t " (without all the spaces).  Very strange.
