### ISSUE TITLE
Creating a block in objc

### ISSUE THREAD

**Issue by Noitidart** [trueinteractions/tint2#161]
Hi there I was very curious, do you know what this code here is doing:

https://github.com/trueinteractions/tint2/blob/638853d4c7e27570b52ec3af2b286fb5b9ff3755/modules/Application/Application_mac.js#L91-L115

      this.blockCallback = $(function(self, arg) {
        if(arg('type') == $.NSKeyDown) {
          var modifierFlags = arg('modifierFlags');
          var alphashift = modifierFlags & $.NSAlphaShiftKeyMask ? true : false,
              shift = modifierFlags & $.NSShiftKeyMask ? true : false,
              ctrl = modifierFlags & $.NSControlKeyMask  ? true : false,
              cmd = modifierFlags & $.NSCommandKeyMask ? true : false,
              alt = modifierFlags & $.NSAlternateKeyMask ? true : false,
              num = modifierFlags & $.NSNumericPadKeyMask ? true : false,
              help = modifierFlags & $.NSHelpKeyMask ? true : false,
              fn = modifierFlags & $.NSFunctionKeyMask ? true : false,
              key = arg('charactersIgnoringModifiers').toString().toLowerCase();
          hotKeys.forEach(function(item) {
            if( ((item.modifiers.indexOf('alt') > -1 && alt) || (item.modifiers.indexOf('alt') === -1 && !alt)) &&
              ((item.modifiers.indexOf('ctrl') > -1 && ctrl) || (item.modifiers.indexOf('ctrl') === -1 && !ctrl)) &&
              ((item.modifiers.indexOf('cmd') > -1 && cmd) || (item.modifiers.indexOf('cmd') === -1 && !cmd)) &&
              ((item.modifiers.indexOf('shift') > -1 && shift) || (item.modifiers.indexOf('shift') === -1 && !shift)) && 
              key === item.key) 
            {
              item.func();
            }
          });
        }
        return arg;
      }.bind(this), ['@',['@','@']]);

I'm curious, this is creating a objc callback, so I'm curious what this `$` is doing. Is it calling `objc_impGetBlock` or something, is it creating a class and adding this as a method to it? I notice the `@@@` thats why im asking.

very interesting stuff.

**Comment by Noitidart** [comment]
So it seems it calls:

https://github.com/trueinteractions/tint2/blob/638853d4c7e27570b52ec3af2b286fb5b9ff3755/modules/Bridge/index.js#L212

    return Import.createBlock(o,m);

Which does:

https://github.com/trueinteractions/tint2/blob/f6ce18b16ada165b98b07869314dad1d7bee0252/modules/Bridge/core.js#L377-L394

```
  /**
   * Creates a C block instance from a JS Function.
   * Blocks are regular Objective-C objects in Obj-C, and can be sent messages;
   * thus Block instances need are creted using the core.wrapId() function.
   *
   * @api private
   */
  function createBlock (func, type) {
    if (!func) {
      return null;
    } else if (func.pointer) {
      return func.pointer;
    }
    var bl = new __block_literal_1;
    // Set the class of the instance
    bl.isa = CGB || (CGB = dlopen().get('_NSConcreteGlobalBlock'));
    // Global flags
    bl.flags = 1 << 29;
    bl.reserved = 0;
    bl.invoke = createWrapperPointer(func, type);
    bl.descriptor = BD.ref();
    var reffed = bl.ref();
    //console.assert(!objc.object_getClass(reffed).isNull(), reffed.inspect());
    return reffed;
  }
```

So here we see were returning the address to a structure that looks like:
https://github.com/trueinteractions/tint2/blob/f6ce18b16ada165b98b07869314dad1d7bee0252/modules/Bridge/core.js#L347-L353

```
  /**
   * We have to simulate what the llvm compiler does when it encounters a Block
   * literal expression (see `Block-ABI-Apple.txt` above).
   * The "block literal" is the struct type for each Block instance.
   */
  var __block_literal_1 = struct({
    isa: 'pointer',
    flags: 'int32',
    reserved: 'int32',
    invoke: 'pointer',
    descriptor: 'pointer'
  });
```

So I had some questions in here, what does `dlopen().get('_NSConcreteGlobalBlock')` do? Then what does `1 << 29` for flag mean`? Very interesting stuff. Then the descriptor struct is populated too. Very interesting!

**Comment by Noitidart** [comment]
Got it, thank you very much for this open source work, I was doing js-ctypes from Firefox and needed to create a block. This was absolutely awesome! Thank you!

This is my code in js-ctypes: https://gist.github.com/Noitidart/8645b47b0e46a0eb284e#file-_ff-addon-snippet-objc_monitorevents-js-L107-L168

**Comment by trevorlinton** [comment]
@Noitidart 

Happy to help, the project and parts of the code you're seeing are based off of upstream nodobjc which I also help maintain (https://github.com/tootallnate/nodobjc/).  It's part of our native bridge that lets Tint execute objective-c, c# and other OS classes directly from javascript (although a bit funky syntax).

The __block_literal_1 creates a standard objective-c block, we extract the symbol for the block from NSConcreateBlock, give it some default flags (1 << 29) so it'll execute correctly then extract the pointer to it and send it off to objective-c land to do callbacks etc..  Note that the execution portion also needs to manage executing it on the correct thread (both incoming and outgoing) which is handled by https://github.com/trueinteractions/tint2/blob/master/modules/Bridge/ffi.cc

Happy hacking.

**Comment by Noitidart** [comment]
Thanks so much for such a fast response and the extra detail on the thread stuff! :)

**Comment by Noitidart** [comment]
Hey @trevorlinton I think you mentioned you had worked on a javascript/ffi thing which could do C#, may you please point me to that, I was hoping to figure out how to do C# from js-ctypes in Firefox.

We do objective-c in firefox like this: https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Examples/Using_Objective-C_from_js-ctypes

So I wanted to draft a page on how to use C# dll's
