### ISSUE TITLE
[Question] Will borderless mode be supported?

### ISSUE THREAD

**Issue by Webkitnote** [trueinteractions/tint2#168]
It would be cool if Tint2 could support borderless mode, where developpers could create their own GUI for management of application and to make themselves look more professional, instead of this very standard Windows buttons and window.

edit:   :s I thought that if I add "[question]", system will catch the tag and mark it :(, I'm sorry, my bad.

**Comment by trevorlinton** [comment]
See creating a transparent (or borderless/splash screen) here:

http://www.trueinteractions.com/tint2/docs/tutorial-windows.html

Depending on the frame type you'll need to manage all of the resizing/close/maximize/minimize events.

Feel free to close this out if it satisfies your needs.
