### ISSUE TITLE
Min-width / min-height for Window?

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#170]
Currently there's no easy possibility to restrict desktop's window resizing, am I right?

<img src="https://dl.dropboxusercontent.com/u/100463011/tint-min-dimensions.gif" width="500" />

**Comment by trevorlinton** [comment]
We've added minimumWidth, minimumHeight, maximumHeight and maximumWidth to the window object, strange how we never saw this missing before :/.  This will be added in 2.2.1 due out tomorrow.

Thanks for reporting this!

See commit: https://github.com/trueinteractions/tint2/commit/c7dccba87243ce350e06df130345ade7544bccdd
