### ISSUE TITLE
How to change the input method like google pinyin el.

### ISSUE THREAD

**Issue by LeiO-Angel** [trueinteractions/tint2#173]
I want to change the input method using the linux tool: xdotool,, but i can do it, cause my web app develop by nwjs(node+webkit). The tint2 ，seems like can do the jobs. somebody can answer, ths!!

**Comment by trevorlinton** [comment]
@LeiO-Angel 

You can control and move the mouse, click on elements on screen, or input text using the System class, for example System.clickAt(x,y) clicks at the specified x, y coordinates on the screen, see:
http://www.trueinteractions.com/tint2/docs/System.html#clickAt

Feel free to reopen if you have further clarifications.
