### ISSUE TITLE
typeof window.postMessageToHost is undefined

### ISSUE THREAD

**Issue by benpptung** [trueinteractions/tint2#175]
Sorry, I am new to tint.
To make it easy to develop app, I choose to develop js app in webview, so I can avoid something I am not familiar to use tint Node.js context. However, I see I cannot use window.postMessageToHost to communicate to tint Node.js context. The result of typeof window.postMessageToHost is undefined. I find no more documentation to figure out why. Is there any document to explain more window.postMessageToHost ? So I send message to tint Node.js context from webview js context.

Thank you very much :)

**Comment by benpptung** [comment]
I've figured out how to get window.postMessageToHost.
Thank you for the examples found in the followings:

https://github.com/trueinteractions/tint2/blob/master/test/assets/webview-echo-test.html
https://github.com/trueinteractions/tint2/blob/master/test/assets/webview-newwindow.html
https://github.com/trueinteractions/tint2/blob/master/test/assets/webview-resources.html

Due to lack of documentation, my understanding of `postMessageToHost` is not exist initially with `window`. We need to wait tint context to `execute` after the webview load event is triggered or at least 1 second till tint add `postMessageToHost` to window.

**Comment by trevorlinton** [comment]
@benpptung It should be available after the on load event in the Window,

e.g.,

```javascript
window.addEventListener('load', function() {
console.log(typeof(window.postMessageToHost)); // == should equal a [ Function ]
});
```

**Comment by benpptung** [comment]
@trevorlinton thank you for the great project and your answer :)

Actually, I've tried to wait the window `load` event since I see the following example code , but I didn't get `window.postMessageToHost`, maybe I am wrong, I'll try again. Just for your information.

https://github.com/trueinteractions/tint2/blob/master/test/assets/webview-resources.html
