### ISSUE TITLE
Built .Exe not opening

### ISSUE THREAD

**Issue by ricmed205** [trueinteractions/tint2#176]
Hi, I installed tint with the latest MSI (I have win10x64). Built the Getting Started app. The built succeded but when running the .exe, nothing happens.

BTW, will a .exe app run in any machine if I have a node script that uses a node-gyp is dependant/built (selenium-webdriver in my example)?

Also, how do you use the --windows-runtime arg (I assume it is to build x32, x64 versions?)? what are the options?

**Comment by trevorlinton** [comment]
@ricmed205 We've resolved this in Tint 2.2.3, it had to do with a regression between Windows 10 and Windows 8.1/7. Please let me know if you continue to have problems (or feel free to reopen this issue).
