### ISSUE TITLE
Global Hotkey pass-through - global keyboard event listener

### ISSUE THREAD

**Issue by MadLittleMods** [trueinteractions/tint2#180]
Add an option to the [global hotkey's](https://www.trueinteractions.com/docs/Application.html#registerHotKey) that allows you to capture input but not consume it. This could instead be covered by a way to listen to any keyboard events happening at a global level.

My use case is making an app that adds an always-on-top overlay WASD that reacts to actual keyboard input.

---

API wise(ideas), this could be accomplished by defaulting to pass-though and add [`e.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) to stop it bubbling.

```js
application.registerHotKey('m','ctrl',function(e) { 
  //e.preventDefault();
});
```

---

Similar issues on other repos:

 - https://github.com/nwjs/nw.js/issues/3503
 - https://github.com/atom/electron/issues/1338

**Comment by trevorlinton** [comment]
@MadLittleMods This is a bit more difficult of a problem than one might be aware.  Operating systems take active steps to prevent applications from doing this.  Using registerHotKey actually does ask for a global trap on all key events.  The OS generally denies these unless the user has explicitly marked the application as an accessibility app or the installation program for the application registered it as an accessibility app.

Having an installer register something as an accessibility app requires the user to explicitly trust the application then enter their root password. You'll find 9/10 times your application will not be permitted this functionality.  I should note this isn't a limitation of Tint, but every application regardless of the language, framework or development approach.

Unfortunately we have to mark this as won't fix as there's little that we know of that can resolve it.  If you have additional information or use cases you'd like to bring up feel free to reopen.

**Comment by trevorlinton** [comment]
BTW, if you want to try your luck at this using the native API's you can see our implementation of this here: 

https://github.com/trueinteractions/tint2/blob/master/modules/Application/Application_mac.js#L87

You can use the same code in your app, it accessing the native API's to try and register hotkeys.

Good luck.

**Comment by MadLittleMods** [comment]
I mainly use a Windows machine where I don't think there are any limitations on this. For other platforms, having the accessibility app limitation or even a prompt for extra permissions wouldn't be a issue for my use case.

At least for Windows, this looks possible by adding an event emitter in here (not sure if that is called for keys that aren't registered): https://github.com/trueinteractions/tint2/blob/fb925bbb217eb44c62b7692b9ec0f4ff400d811b/modules/Application/Application_win.js#L28
