### ISSUE TITLE
Is it possible to create an EventListener for the backspace key?

### ISSUE THREAD

**Issue by janoelze** [trueinteractions/tint2#184]
I want to remove the selected table row, when the backspace key is pressed.

I tried this: 

```
application.registerHotKey('\uf728', function(){
    console.log('del-event');
});
```

throwing: "TypeError: item.modifiers.indexOf is not a function at Application.js:104:34"

and this:

```
application.registerHotKey('^h', function(){
    console.log('del');
});
```

exiting with "AssertionError: A global hot key may only have one character."

Any solutions for this? Thanks in advance!

Key-Codes From: http://osxnotes.net/keybindings.html and ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/CORPCHAR.TXT

**Comment by bral** [comment]
@janoelze the unicode escape sequence you're looking for is `\u007f` and you'll want to pass an empty string as the second argument since you don't want any modifiers.
```
application.registerHotKey('\u007f', '', function() {
  // Cool stuff here
}
```

Hope that helps!

Closing this issue. Feel free to reopen if you have further issues.

**Comment by janoelze** [comment]
perfect, thanks!
