### ISSUE TITLE
`appearance-change` event name doesn't match documentation

### ISSUE THREAD

**Issue by cwillisf** [trueinteractions/tint2#190]
The actual event fired when the UI appearance changes on OS X is `appearance-change`:
https://github.com/trueinteractions/tint2/blob/master/modules/Application/Application_mac.js#L571

On the other hand, the documentation claims that the event is called `appearance-changed`:
https://www.trueinteractions.com/tint2/docs/Application.html#appearance-changed
https://github.com/trueinteractions/tint2/blob/master/modules/Application/Application_mac.js#L560

Handling `appearance-change` works fine, but I had to look at the Tint source code to figure out why `appearance-changed` wasn't working for me :)

**Comment by trevorlinton** [comment]
@cwillisf Thanks for reporting this, we've fixed the event, both appearance-change and appearance-changed are now supported.  This will be available in the next release due out 3/21.
