### ISSUE TITLE
Hmm. Nothing happens when I run tint main.js

### ISSUE THREAD

**Issue by Dillybob92** [trueinteractions/tint2#191]
So I followed this tutorial:

https://www.trueinteractions.com/docs/tutorial-gettingstarted.html

Look:

![image](https://cloud.githubusercontent.com/assets/10387670/14130518/50b80d24-f5e8-11e5-82f5-020d27557691.png)

Nothing happens.. any idea? :package: 
Windows 7, 64 bit here.

Looking to get my 100k + LOC Game over to Tint from Electron. Cannot stand Chromium's RequestAnimationFrame functionality on minimized windows

**Comment by trevorlinton** [comment]
@Dillybob92 This was an error in a previous release of Tint, can you try downloading v2.3.6 or above and feel free to reopen this if you continue to have issues.
