### ISSUE TITLE
Unicode problems with .NET bridge.

### ISSUE THREAD

**Issue by Guevara-chan** [trueinteractions/tint2#195]
`tmp = $.System.IO.Path.GetFullPath("C:\\Utils\\JScript\\Projects\\Ælfgen")
$.System.IO.Directory.GetDirectories(tmp)`
Just a little piece of code to get list of subdirs from path, containing non-ASCII characters. And whole process goes down the drain:

> { [System.ArgumentException: System.ArgumentException ���� �������� ������������ �����.
   � System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   � System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   � System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   � System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   � System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   � System.IO.Directory.GetDirectories(String path)]
  Message: '���� �������� ������������ �����.',
  ParamName: null,
  Data: <Buffer@0x000001FC26B2AE30 28 ce 70 28 fc 01 00 00>,
  InnerException: null,
  TargetSite: <Buffer@0x000001FC26B2AE28 28 d1 70 28 fc 01 00 00>,
  StackTrace: '   � System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)\r\n   � System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)\r\n   � System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)\r\n   � System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)\r\n   � System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)\r\n   � System.IO.Directory.GetDirectories(String path)',
  HelpLink: null,
  Source: 'mscorlib',
  HResult: -2147024809,
  message: 'System.ArgumentException ���� �������� ������������ �����.\n   � System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)\r\n   � System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)\r\n   � System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)\r\n   � System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)\r\n   � System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)\r\n   � System.IO.Directory.GetDirectories(String path)',
  name: 'System.ArgumentException' }

...Why so ? Well, mostly because:
`tmp = $.System.IO.Path.GetFullPath("C:\\Utils\\JScript\\Projects\\Ælfgen")`
`console.log tmp == "C:\\Utils\\JScript\\Projects\\Ælfgen"`

...seems to be:
> false

Still, why so ? Well, let's analyze a bit deeper:
`console.log new Buffer($.System.IO.Path.GetFileName("Æ"))`
`console.log new Buffer("Æ")`

...Bingo:
`> <Buffer@0x000001E29D3205A0 3f>`
`> <Buffer@0x000001E29D3205A8 c3 86>`

**Comment by trevorlinton** [comment]
Can you try release 2.3.9? It should hopefully fix your issues.

If not, feel free to reopen this.

**Comment by Guevara-chan** [comment]
Um... Zero changes, unfortunately:
`console.log new Buffer($.System.IO.Path.GetFileName("Æ"))`
`console.log new Buffer("Æ")`

...still equals to:
`<Buffer@0x0000025D3B018F88 3f>`
`<Buffer@0x0000025D3B018F90 c3 86>`
