### ISSUE TITLE
Unicode problems with .NET bridge [2]

### ISSUE THREAD

**Issue by Guevara-chan** [trueinteractions/tint2#199]
Well, it's 2.3.9 already and we still can't have nice things:

`console.log(new Buffer($.System.String.Copy("Æ")))`
`console.log(new Buffer("Æ"))`
...goes down to good old:
`<Buffer@0x000001A6A397B618 3f>`
`<Buffer@0x000001A6A397B620 c3 86>`

Even after all supposed fixes since #195.

**Comment by trevorlinton** [comment]
Well crap. I forgot again to use a coaster on the coffee table. Well take a closer look. Sorry. Perhaps the string encodings between v8 and .net aren't so UTF8 compatible. I believe there's some interm c++ transitions that might be mucking up the data, either that or when it's copied out of v8 were accidently coping an ascii string and not the backing memory. I'd be pretty surprised if either v8 or .net didn't use UTF8 by default.

**Comment by trevorlinton** [comment]
I've titled 2.3.10 release "we can have nice things".  I hope this resolves the unicode issues in Windows, please close this issue if it does, if not please provide more information.  We've added a new unit test https://github.com/trueinteractions/tint2/blob/master/test/unicode.js to ensure we preserve unicode characters. 

You can find the new release here: https://github.com/trueinteractions/tint2/releases/tag/2.3.10

We do appreciate you filing these bugs; we heavily rely on users like you to report issues so we can help make tint exceed your expectations.

**Comment by Guevara-chan** [comment]
It... Works 0_0
`<Buffer@0x0000018898CC7570 c3 86>`
`<Buffer@0x0000018898CC7578 c3 86>`

Thank you very much, I guess.
