### ISSUE TITLE
Optional icon

### ISSUE THREAD

**Issue by Jellyfrog** [trueinteractions/tint2#67]
If would be nice if the icon would be optional when making background apps.

Best way would be to set `LSUIElement` to  `1` I suppose; https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256

**Comment by trevorlinton** [comment]
@Jellyfrog This has been fixed.  We've added an option 'process.background' that if set to true prior to using require('Common') or require('Application') it will not show the app in the task bars/docks and other interface items.  It'll be ready for 2.0.10 to be released tomorrow.
