### ISSUE TITLE
Animation support for Controls and Containers

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#79]
Is it possible to add animation support for different controls, for example like it's added on `Window` object - https://github.com/trueinteractions/tint2/blob/master/test/window-bounds.js#L20?

**Comment by trevorlinton** [comment]
@voronianski  BTW, the property has moved from control.preferences.animate* to just control. (no preferences).  In addition its now on the control object rather than just the window, so it can be used on any Control object.
