### ISSUE TITLE
Box bounds return `null`

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#84]
I just found out that `Box` class has no `bounds` property (https://www.trueinteractions.com/tint2/docs/Control.html#bounds).

I think it's important to have access to real dimensions and position in order to implement custom controls like tabs etc. 

In this rough example in order to properly align next tab we need to know actual width of the previous one in pixels:

```javascript
var tab1 = new Box();
var tab2 = new Box();
var tabCount = 2;
var tabHeight = 25;

tab1.width = (100/tabCount)+'%';
tab1.height = tabHeight;
tab1.borderWidth = 0;
tab1.backgroundColor = '#ECECEC';
tab1.top = 0;
tab1.left = 0;

tab2.width = (100/tabCount)+'%';
tab2.height = tabHeight;
tab2.borderWidth = 0;
tab2.backgroundColor = '#F6F6F6';
tab2.top = 0;
// tab2.left = tab1.bounds.width + 5; // exception thrown
console.log(tab1.bounds) // -> null

mainWindow.sharedInstance.appendChild(tab1);
mainWindow.sharedInstance.appendChild(tab2);
```

**Comment by trevorlinton** [comment]
@voronianski The bounds can only be determined once the item has been added to a control, does the console.log(tab1.bounds) work after its been appended to the main window? (it should return null if it has not yet be placed on a target)

**Comment by voronianski** [comment]
@trevorlinton yep, sorry
