### ISSUE TITLE
WebView backgroundColor?

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#87]
There's no way to change background color of web view, is it by design?

I thought it could be possible to make web view transparent and draw complete UI with html/css.

**Comment by trevorlinton** [comment]
@voronianski Just a side note, we've started initial builds of a chromium plugin for Tint you can check it out here (windows only for now): https://github.com/trueinteractions/tint-chromium

It supports a transparent background on windows (just like on OS X and as described above).

Unfortunately the IE MSHTML plugin is VERY difficult to get into a mode that supports transparent backgrounds and I believe it would be better to spend time supporting the chromium optional plugin for more advanced browser use-cases than try and support transparency in IE/Windows. That said, remember that transparency is supported without chromium out of the box on OSX.

Let me know if you have further questions, if you feel its not an optimal solution feel free to reopen this.

Thanks,
Trevor
