### ISSUE TITLE
Disable right click menu in WebView

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#90]
Is there a way to disable right clicked menu in WebView?

**Comment by voronianski** [comment]
@trevorlinton never mind :)

**Comment by 7immy** [comment]
I'm guessing you're referring to the reload option in the menu. If so did you find out how to remove this?

**Comment by trevorlinton** [comment]
@7immy You can do this with HTML/CSS (I do believe all the browsers support it)

See: http://stackoverflow.com/questions/737022/how-do-i-disable-right-click-on-my-web-page

**Comment by 7immy** [comment]
Sounds like the answer. Cheers @trevorlinton
